### ISSUE TITLE
 @pact-foundation/pact/dist/pact does not exist in pact foundation folder

### ISSUE THREAD

**Issue by jathniel** [YOU54F/jest-pact#143]
I Receive this error after running the test:
```
    Cannot find module '@pact-foundation/pact/dist/pact' from 'index.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (node_modules/jest-pact/index.js:14:12)
```
the folder /dist/pact does not exist in @pact-foundation/pact
**Versions of the packages**
```
    "@pact-foundation/pact": "^9.5.0",
    "jest": "^24.9.0",
    "jest-pact": "^0.5.0-beta"
```

**Comment by jathniel** [comment]
Node: v12.13.1
npm:  6.12.1

**Comment by YOU54F** [comment]
please use the non beta version `0.4.5` and let me know if you get the same

**Comment by jared-fraser** [comment]
Confirm getting the same message with `^0.5.0-beta`, however no message with `0.4.5`

**Comment by TimothyJones** [comment]
You should be fine to not use the beta version of jest-pact - it existed to test a beta version of pact-js, which might have impacted windows users.

The changes in the pact-js beta are now in the main release, so there's no value in using the beta jest-pact.

**Comment by YOU54F** [comment]
@jared-fraser a new version will be release in the next 20 mins or so, `0.5.2` with updated deps. 👍
